spring:
  cloud:
    stream:
      default:
        group: BlockRetry
        producer:
          header-mode: none
        consumer:
          maxAttempts: 11
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}
          configuration:
            security:
              protocol: PLAINTEXT
        bindings:
          default:
            consumer:
              ack-mode: record
        default:
          content-type: application/json
          consumer:
            start-offset: earliest
      bindings:
        default:
          content-type: application/json
        # Consumer kafka topic
        blockRetryConsumer-in-0:
          destination: BlockRetry
          consumer:
            max-attempts: 4
    function:
      definition: blockRetryConsumer

